### PR TITLE
Make .so directly. Without fake executable

### PR DESCRIPTION
**Pull request by zayass**
PackageDescriptionV4 used

This workaround from plugin no more needed
```bash
if [[ "$*" =~ " -emit-executable " ]]; then
    LINKER_ARGS="-Xlinker -shared -Xlinker -export-dynamic -tools-directory $SWIFT_INSTALL/usr/$ARCH"
fi
```

### CODE REVIEW

**Comment by johnno1962** [comment]
Thanks! Is there any way to make this work with a swift3 Package.swift? Xcode 9 is still in beta so I can’t merge this just yet. If I leave the workaround in but someone uses PackageDescriptionV4 do things still work?

**Comment by zayass** [comment]
I think no. But Xcode 9 is very close release. And it is very simple to switch between 8/9.
Yes V4 will work with or without ```-Xlinker -shared ```
But with this is impossible to make really executable

**Comment by johnno1962** [comment]
I think we’ll need to leave LINKER_ARGS in for the -tools-directory which is probably still required on Linux. This PR may is a bit related: https://github.com/apple/swift/pull/11510. I’m interested to see the options SPM uses passes to swiftc to generate a shared library the right way. The correct fix is to use job.getKind() != LinkKind::DynamicLibrary. Have you captured the command for the link?

**Comment by zayass** [comment]
I capture swiftc calling with `-v` but not linker invocation.
In swift call `-emit-library` and `-o path/name.dylib` looks like all changes

**Comment by zayass** [comment]
About  tools-directory why you add this only for "executable"

**Comment by johnno1962** [comment]
I use it to find the right ld.gold. Otherwise you have to patch it into /usr/bin under the name /usr/bin/armv7-none-linux-androideabi-ld.gold as part of the install.

**Comment by zayass** [comment]
```bash
export PATH="$SWIFT_INSTALL/usr/Darwin:$SWIFT_INSTALL/usr/bin:$PATH"
```

in swiftc-android.sh
is not enough for it?

on macOS as I see correct binaries compiled without this flag

**Comment by zayass** [comment]
And what about xctest. I see you compile .so/swiftmodule. 
Do you plan to include them to tollchain?

What do you think about this https://github.com/SwiftJava/swift-android-gradle/pull/2?
I think I can add some gradle task to that plugin for running tests on device simpler

**Comment by johnno1962** [comment]
At the moment I patch swiftc-android to switch from executable to library and run the tests :D Give me a chance to digest your changes and see if what you’re proposing is compatable with keeping v3 Package.swift working which would be my preference for now. Do you have an example project with a test on github I can look at?

**Comment by zayass** [comment]
I test on this sample, on very simple project which I send you by email and this https://github.com/zayass/swift-android-libxml-prebuilt/tree/master

It is "compatible". As you can see in this project you can mix v3 and v4 packages. But if you want to build all staff as shared library you need one v4 package for it

**Comment by johnno1962** [comment]
This all looks very promising. V4 packages seem to be way better than V3. It’s just that they imply the code will be compiled with Swift 4 as well. Ok, for the root package I suppose.

**Comment by zayass** [comment]
I think is no reason to wait for xcode 9 release. Android toolchain itself already swift 4. The final version will be available within one month. So I think no major changes between beta 6 and GM

**Comment by johnno1962** [comment]
I think I can have my cake and eat it as they say. I’ve modified swiftc-android.sh for V4 but with a compatibility "if" for V3 users. I’d rather not have Xcode 9 as a requirement for a few months yet.
```#!/bin/bash
#
# Substitutes in for swiftc to compile package and build Android sources
#

SWIFT_INSTALL="/home/johnno/swifty-robot-environment/util/prepare_environment/swift-install"
export PATH="$SWIFT_INSTALL/usr/Linux:$SWIFT_INSTALL/usr/bin:$PATH"

if [[ "$*" =~ " -fileno " ]]; then
    swift "$@" || (echo "*** Error executing: $0 $@" && exit 1)
    exit 0
fi

ARGS=$(echo "$*" | sed -E "s@-target [^[:space:]]+ -sdk /[^[:space:]]* (-F /[^[:space:]]* )?@@")

if [[ "$ARGS" =~ " -emit-executable " && "$ARGS" =~ ".so " ]]; then
    ARGS=$(echo "$ARGS" | sed -E "s@ -emit-executable @ -emit-library @")
fi

swiftc -target armv7-none-linux-androideabi -sdk "$SWIFT_INSTALL/ndk-android-21" \
    -L "$SWIFT_INSTALL/usr/Linux" -tools-directory "$SWIFT_INSTALL/usr/Linux" \
    $ARGS || (echo "*** Error executing: $0 $ARGS" && exit 1)
```
For V4 users all it does now is patch in the -target/sdk rather than use destination filles.

**Pull request closed without merging**
